# Due to how Astro handles type inference with this structure,
# we need to prefix all configuration keys with an underscore.

[_.site]
baseUrl = "http://localhost:4321"

[_.globalMeta]
title = "Zhr's portfolio"
description = "Student game designer and computer science enthusiast"
cardImage = "http://localhost:4321/literally_me.jpg"
keywords = ["game development", "gamedev", "gamedesign", "game design", "game designer", "gd"]

[_.blogMeta]
title = "Zhr's blog"
description = "Notes about gamedev"
longDescription = "Gamedev and game design staff"
cardImage = "http://localhost:4321/literally_me.jpg"
keywords = ["game development", "game design", "technology"]

[_.projectMeta]
title = "Zhr's projects"
description = "A list of my game development projects."
cardImage = "http://localhost:4321/literally_me.jpg"
longDescription = "My projects include ttrpg, computer game, and tabletop works."
keywords = ["game development", "ttrpg", "games"]

[_.notFoundMeta]
title = "idk 404"
description = "The page you are looking for does not exist."
longDescription = "The page you are looking for does not exist. Maybe it never existed. Spooky."

[_.hero]
title = "Samokhvalov Zakhar"
subtitle = "Student game designer &<br />computer science enthusiast"
ctaText = "View Projects"
image = "https://localhost:4321/literally_me.jpg"
ctaUrl = "/projects"

[_.personal]
name = "Zhr"
githubProfile = "https://github.com/zhr0451"
cardImage = "http://localhost:4321/literally_me.jpg"

[_.texts]
articlesName = "Articles"
projectsName = "Projects"
viewAll = "View All"
noArticles = "No articles found."
noProjects = "No projects found."

[_.menu]
home = "/"
projects = "/projects"
blog = "/blog"